[project]
name = "test-dbx-delta-share-access"
version = "1.0.0"
description = "python script to test access to databricks delta sharing data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "delta-sharing>=1.4.1",
    "pandas>=3.0.0",
]

