[project]
name = "test-dbx-delta-share-access"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "delta-sharing>=1.4.1",
    "pandas>=3.0.0",
]

